# Generated by Django 2.1.3 on 2019-05-27 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=128, verbose_name='文件完整路径')),
                ('file_size', models.CharField(max_length=128, verbose_name='文件大小')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, max_length=128, verbose_name='文件上传的日期和时间')),
                ('upload_user', models.CharField(blank=True, max_length=128, verbose_name='上传文件的用户')),
            ],
            options={
                'db_table': 'app_upload_file_info',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='邮箱')),
                ('login_time', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
            ],
            options={
                'db_table': 'app_user_info',
            },
        ),
    ]
